import type { Metadata } from "next";
import "./globals.css";

import AuthProvider from "./features/(auth)/providers/authProvider";
import { SelectedOrganizationProvider } from "@/context/SelectedOrganizationContext";

export const metadata: Metadata = {
  title: "The Voters",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <SelectedOrganizationProvider>
            {children}
          </SelectedOrganizationProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
