import type { Metadata } from "next";
import "./globals.css";

import { SelectedOrganizationProvider } from "@/context/SelectedOrganizationContext";
import { Toaster } from "sonner";
import { TooltipProvider } from "@/components/ui/tooltip";

export const metadata: Metadata = {
  title: "The Voters",
  description: "Generated by create next app",
  icons: {
    icon: [
      { 
        url: '/icon.svg', 
        type: 'image/svg+xml',
        sizes: '64x64' // or larger like '96x96', '128x128'
      }
    ],
    // apple: {
    //   url: '/icon.svg',
    //   type: 'image/svg+xml',
    //   sizes: '180x180' // Apple recommends 180x180
    // },
    // shortcut: {
    //   url: '/icon.svg',
    //   type: 'image/svg+xml',
    //   sizes: '192x192'
    // }
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SelectedOrganizationProvider>
          <TooltipProvider>{children}</TooltipProvider>
        </SelectedOrganizationProvider>
        <Toaster />
      </body>
    </html>
  );
}