import type { Metadata } from "next";
import "./globals.css";

import { SelectedOrganizationProvider } from "@/context/SelectedOrganizationContext";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "The Voters",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SelectedOrganizationProvider>{children}</SelectedOrganizationProvider>
        <Toaster />
      </body>
    </html>
  );
}
